apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reliability-api
  namespace: reliability-lab
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: reliability-api
