apiVersion: v1
kind: Service
metadata:
  name: reliability-api
  namespace: reliability-lab
  labels:
    app.kubernetes.io/name: reliability-api
spec:
  selector:
    app.kubernetes.io/name: reliability-api
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
